### ISSUE TITLE
Reset Points Function Resets Both Points to 1

### ISSUE THREAD

**Issue by bikeidaho** [JumpShot-Interactive/TeleScore#10]
Expectation: When pressing the "Reset Points" button, I expect both points to be reset back to 0.

Reality: When pressing the "Reset Points" button, both scores are reset to 1.

https://github.com/JumpShot-Interactive/TeleScore/assets/43679674/19d23649-8754-4c95-b6cc-b54f0fec5d7a

**Comment by OtamakSK** [comment]
You can fix it by changing "Set Amount" in "Set Properties" in properties of this button in Edit mode
